spring:
  mail:
    host: smtp.gmail.com
    port: localhost
    email: sender@gmail.com
    subject: Booking Confirmation
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port : 8081